universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute_hlcv.sh

arguments               = run_experiment.py --config ftw_mask_baseline

output                  = /home/hlcv_teamxxx/condor_logs/ftw_mask_baseline.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_teamxxx/condor_logs/ftw_mask_baseline.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_teamxxx/condor_logs/ftw_mask_baseline.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 2
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
